apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stag-wordpress
  name: wordpress-deployment
  labels:
    app: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-deployment
  template:
    metadata:
      labels:
        app: wordpress-deployment
    spec:
      containers:
      - name: wordpress-deployment
        image: fiardika/staging-wordpress-jenkins:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  namespace: stag-wordpress
  name: wordpress-service
spec:
  selector:
    app: wordpress-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: stag-wordpress
  name: ingress
spec:
  rules:
  - host: blog-staging.fiardika.xyz
    http:
      paths:
        - backend:
           serviceName: wordpress-service
           servicePort: 80
